# Generated by Django 2.1 on 2018-11-17 20:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('book', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='book',
            name='Book_Name',
            field=models.CharField(max_length=40),
        ),
        migrations.AlterField(
            model_name='book',
            name='image',
            field=models.ImageField(null=True, upload_to='static/book_image'),
        ),
        migrations.AlterField(
            model_name='book',
            name='link',
            field=models.CharField(max_length=150, null=True),
        ),
        migrations.AlterField(
            model_name='book',
            name='pdf',
            field=models.FileField(null=True, upload_to='static/book_pdf'),
        ),
    ]
