# Generated by Django 2.1 on 2018-11-17 20:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('book', '0003_auto_20181118_0221'),
    ]

    operations = [
        migrations.AddField(
            model_name='book',
            name='type_of_books',
            field=models.CharField(choices=[('M', 'Mystery'), ('O', 'Other'), ('H', 'Horror'), ('I', 'Inspirational'), ('S', 'Science Fiction')], default='O', max_length=10),
        ),
    ]
